"""
Django settings for netology_pd_diplom project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import sentry_sdk

load_dotenv()


sentry_sdk.init(
    dsn=os.getenv('SENTRY_DSN'),
    send_default_pii=True,
    enable_logs=True,
    traces_sample_rate=1.0,
    profile_session_sample_rate=1.0,
    profile_lifecycle='trace',
)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.getenv('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG')

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']
INTERNAL_IPS = ['127.0.0.1', ]

# Application definition

INSTALLED_APPS = [
    'baton',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'rest_framework',
    'rest_framework.authtoken',
    'django_rest_passwordreset',
    'django_celery_results',
    'debug_toolbar',
    'imagekit',
    'backend',
    'drf_spectacular',
    'social_django',
    'baton.autodiscover',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
    # 'baton.autodiscover.AutodiscoverMixin',
]

ROOT_URLCONF = 'netology_pd_diplom.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'backend', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'netology_pd_diplom.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE'),
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}

AUTHENTICATION_BACKENDS = (
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# social auth configs for github
SOCIAL_AUTH_GITHUB_KEY = os.getenv('GITHUB_CLIENT_ID')
SOCIAL_AUTH_GITHUB_SECRET = os.getenv('GITHUB_CLIENT_SECRET')
SOCIAL_AUTH_GITHUB_SCOPE = ['user:email']  # Запрос email для ассоциации

# social auth configs for google
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.getenv('GOOGLE_CLIENT_ID')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv('GOOGLE_CLIENT_SECRET')
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/userinfo.profile',
]  # Базовые права для профиля

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'


SOCIAL_AUTH_LOGIN_REDIRECT_URL = 'success'      # После успешного входа
SOCIAL_AUTH_LOGIN_ERROR_URL = 'error'           # При ошибке
SOCIAL_AUTH_NEW_USER_REDIRECT_URL = '/auth/success/?new=1'
SOCIAL_AUTH_ADMIN_USER_SEARCH_FIELDS = ['username', 'email']

# Pipeline для кастомизации процесса аутентификации
SOCIAL_AUTH_PIPELINE = (
    # Стандартные шаги social-authINTERNAL_IPS
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',

    # Если пользователь новый — создаём его
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',

    # Кастомный шаг: привязка к существующему пользователю по email
    'backend.pipeline.associate_by_email',

    # Привязка социального аккаунта к пользователю
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',

    # Кастомный шаг: заполнение профиля из GitHub
    'backend.pipeline.set_user_profile_from_github',

    # Финальный шаг
    'social_core.pipeline.user.user_details',
)

SOCIAL_AUTH_ASSOCIATE_BY_EMAIL = True

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

IMAGE_UPLOAD_MAX_SIZE = int(os.getenv('IMAGE_UPLOAD_MAX_SIZE', 5 * 1024 * 1024))
IMAGE_UPLOAD_ALLOWED_FORMATS = tuple(
    item.strip().upper()
    for item in os.getenv('IMAGE_UPLOAD_ALLOWED_FORMATS', 'JPEG,JPG,PNG,WEBP').split(',')
    if item.strip()
)


if DEBUG:
    from django.conf.urls.static import static


AUTH_USER_MODEL = 'backend.User'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_USE_TLS = True

EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.mail.ru')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'netology.diplom@mail.ru')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'CLdm7yW4U9nivz9mbexu')
EMAIL_PORT = os.getenv('EMAIL_PORT', '465')
EMAIL_USE_SSL = True
SERVER_EMAIL = EMAIL_HOST_USER

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_ADMIN = EMAIL_HOST_USER

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 40,

    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),

    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly' if DEBUG
        else 'rest_framework.permissions.IsAdminUser',
    ],

    # Схема по умолчанию для drf-spectacular
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',  # ограничения для анонимных пользователей
        'user': '1000/day', # ограничения для авторизованных пользователей
    }
}

# CACHE для троттлинга
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'throttling',
    }
}


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Конфигурация Celery
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/1')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60

# Конфигурация Flower
CELERY_MONITORING = True
FLOWER_PORT = 5555
FLOWER_BASIC_AUTH = os.getenv('FLOWER_BASIC_AUTH', '')

# Конфигурация DRF SPECTACULAR
SPECTACULAR_SETTINGS = {
    'TITLE': 'Netology Python Final Diplom API',
    'DESCRIPTION': 'API для интернет-магазина: пользователи, товары, заказы, импорт прайс-листов',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,  # Ускорить отдачу Swagger UI

    # Раздельные схемы для запроса/ответа (улучшает читаемость)
    'COMPONENT_SPLIT_REQUEST': True,

    # Настройки аутентификации в Swagger UI
    'SECURITY': [
        {'TokenAuth': []},  # Для DRF TokenAuthentication
    ],
    'COMPONENTS': {
        'securitySchemes': {
            'TokenAuth': {
                'type': 'apiKey',
                'in': 'header',
                'name': 'Authorization',
                'description': 'Авторизация: `Token <ваш_токен>`',
            },
        },
    },

    # Локализация
    'ENUM_NAME_OVERRIDES': {
        'OrderStatusEnum': 'backend.models.Order.Status',
    },

    # Исключение лишних эндпоинтов из документации
    'PREPROCESSING_HOOKS': [
        'drf_spectacular.hooks.preprocess_exclude_path_format',
    ],

    # Пост-обработка схемы
    'POSTPROCESSING_HOOKS': [
        'drf_spectacular.hooks.postprocess_schema_enums',
    ],
}

# Конфигурация BATON
BATON = {
    # Внешний вид
    'SITE_HEADER': 'Netology Diplom Admin',
    'SITE_TITLE': 'Админ-панель',
    'INDEX_TITLE': 'Panel Administration',
    'SUPPORT_HREF': 'https://github.com/VladPrickly/Netology_python_final_diplom',
    'COPYRIGHT': '© 2026 Vlad Prickly',
    # 'POWERED_BY': '<a href="https://github.com/otto-torino/django-baton" target="_blank">otto-torino </a>',
    'CONFIRM_UNSAVED_CHANGES': True,
    'SHOW_MULTIPART_UPLOADING': True,
    'ENABLE_IMAGES_PREVIEW': True,
    'COLLAPSABLE_USER_AREA': False,


    'DEFAULT_THEME': 'light', # Тема по умолчанию: 'light' или 'dark'

    # Графики на дашборде
    'CHARTJS_COLORS': {
        'primary': '#3b82f6',
        'success': '#22c55e',
        'warning': '#f59e0b',
        'danger': '#ef4444',
    },

    # Кастомное меню (левый сайдбар)
    'MENU': (
        # Раздел с иконкой
        {'type': 'title', 'label': 'Основное', 'icon': 'dashboard'},

        # Стандартное приложение
        {'type': 'app', 'name': 'auth', 'label': 'Пользователи', 'icon': 'people'},

        # Конкретная модель
        {'type': 'model', 'app': 'backend', 'name': 'product', 'label': 'Товары', 'icon': 'inventory_2'},
        {'type': 'model', 'app': 'backend', 'name': 'category', 'label': 'Категории', 'icon': 'category'},
        {'type': 'model', 'app': 'backend', 'name': 'order', 'label': 'Заказы', 'icon': 'shopping_cart'},
        {'type': 'model', 'app': 'backend', 'name': 'shop', 'label': 'Магазины', 'icon': 'store'},

        # Внешняя ссылка
        {'type': 'free', 'label': 'Документация API (Swagger)', 'url': '/schema/swagger-ui/', 'icon': 'description',
         'new_browser_tab': True},
        {'type': 'free', 'label': 'Альтернативный интерфейс документации (ReDoc)', 'url': '/schema/redoc/', 'icon': 'description',
         'new_browser_tab': True},

        # Разделитель
        {'type': 'divider'},

        # Ссылка на настройки
        {'type': 'free', 'label': 'Настройки', 'url': '/admin/baton/batonsettings/', 'icon': 'settings'},
    ),

    # Отображение меню
    'MENU_ALWAYS_COLLAPSED': True,  # Меню развёрнуто по умолчанию
    'SHOW_CHANGELIST_FILTERS': True,  # Фильтры в списке объектов

    # Поиск
    'SHOW_MULTIPART_FILTERS': True,  # Фильтры для файловых полей

    # Список объектов (changelist)
    'CHANGELIST_FILTERS_IN_MODAL': True,  # Фильтры в модальном окне
    'CHANGELIST_FILTERS_FORM': True,  # Красивая форма фильтров

    # Редактирование объекта
    'FORM_TABS_BY_FIELDSETS': True,  # Вкладки на основе fieldsets
    'FORM_RENDERING': 'horizontal',  # Горизонтальная форма (более компактная)
}


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {'console': {'class': 'logging.StreamHandler'}},
    'loggers': {
        'social': {'handlers': ['console'], 'level': 'DEBUG', 'propagate': True},
        'django': {'handlers': ['console'], 'level': 'INFO'},
    },
}